parameters:
    env(PHPCR_WORKSPACE): 'default'

sulu_document_manager:
    sessions:
        default:
            backend: '%app.phpcr_backend%'
            workspace: "%env(PHPCR_WORKSPACE)%"
            username: "%env(PHPCR_USER)%"
            password: "%env(PHPCR_PASSWORD)%"
        live:
            backend: '%app.phpcr_backend%'
            workspace: "%env(PHPCR_WORKSPACE)%_live"
            username: "%env(PHPCR_USER)%"
            password: "%env(PHPCR_PASSWORD)%"
