parameters:
    env(ELASTICSEARCH_HOST): '127.0.0.1:9200'
    env(ELASTICSEARCH_INDEX): 'suludemo'

sulu_core:
    content:
        structure:
            default_type:
                article: 'blog'

sulu_article:
    index_name: '%env(resolve:ELASTICSEARCH_INDEX)%'
    hosts:
        - '%env(resolve:ELASTICSEARCH_HOST)%'

sulu_route:
    mappings:
        Sulu\Bundle\ArticleBundle\Document\ArticleDocument:
            generator: 'schema'
            options:
                route_schema: '/blog/{object.getTitle()}'
        Sulu\Bundle\ArticleBundle\Document\ArticlePageDocument:
            generator: 'article_page'
            options:
                route_schema: '/{translator.trans("page")}-{object.getPageNumber()}'
                parent: '{object.getParent().getRoutePath()}'
