parameters:
    env(PHPCR_WORKSPACE): 'default'

sulu_document_manager:
    sessions:
        default:
            backend: '%app.phpcr_backend%'
            workspace: "%env(PHPCR_WORKSPACE)%"
            username: admin
            password: admin
        live:
            backend: '%app.phpcr_backend%'
            workspace: "%env(PHPCR_WORKSPACE)%_live"
            username: admin
            password: admin
