version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - ${DOCKER_MYSQL_PORT:-3306}:3306
    volumes:
      - ./var/data/mysql:/var/lib/mysql:cached
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  elasticsearch:
    image: elasticsearch:6.8.9
    ports:
      - ${DOCKER_ES_PORT:-9200}:9200
    volumes:
      - ./var/data/elasticsearch:/usr/share/elasticsearch/data:cached
    environment:
        ES_JAVA_OPTS: "-Xms750m -Xmx750m"
