sulu_automation_api:
    resource: '@SuluAutomationBundle/Resources/config/routing_api.yml'
    prefix: /admin/api

sulu_automation:
    type: rest
    resource: '@SuluAutomationBundle/Resources/config/routing.yml'
    prefix: /admin/automation
