{{- if .Values.elasticsearch.enabled }}
apiVersion: v1
kind: Service
metadata:
    name: {{ include "elasticsearch.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "elasticsearch.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    type: NodePort
    ports:
        - port: 9200
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "elasticsearch.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
