{{- if .Values.elasticsearch.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ include "elasticsearch.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "elasticsearch.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    replicas: 1
    serviceName: {{ include "elasticsearch.fullname" . }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ include "elasticsearch.fullname" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
    volumeClaimTemplates:
        - metadata:
              name: {{ include "elasticsearch.fullname" . }}-data
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 16Gi
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ include "elasticsearch.fullname" . }}
                app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
            initContainers:
                - name: volume-permissions
                  image: busybox
                  command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
                  volumeMounts:
                      - name: {{ include "elasticsearch.fullname" . }}-data
                        mountPath: /usr/share/elasticsearch/data
            containers:
                - name: {{ include "elasticsearch.fullname" . }}
                  image: "docker.elastic.co/elasticsearch/elasticsearch:6.8.3"
                  env:
                      - name: ES_JAVA_OPTS
                        value: "-Xms512m -Xmx512m"
                      - name: discovery.type
                        value: "single-node"
                      - name: xpack.security.enabled
                        value: "false"
                  volumeMounts:
                      - name: {{ include "elasticsearch.fullname" . }}-data
                        mountPath: /usr/share/elasticsearch/data
                  ports:
                      - name: http
                        containerPort: 9200
                        protocol: TCP
                  readinessProbe:
                      httpGet:
                          path: /
                          port: http
                  livenessProbe:
                      httpGet:
                          path: /
                          port: http
{{- end }}
