apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: {{ include "jackrabbit.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "jackrabbit.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    replicas: 1
    serviceName: {{ include "jackrabbit.fullname" . }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ include "jackrabbit.fullname" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
    volumeClaimTemplates:
        - metadata:
              name: {{ include "jackrabbit.fullname" . }}-data
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 8Gi
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ include "jackrabbit.fullname" . }}
                app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
            containers:
                - name: {{ include "jackrabbit.fullname" . }}
                  image: "{{ .Values.jackrabbit.image.repository }}:{{ .Values.jackrabbit.image.tag }}"
                  imagePullPolicy: {{ .Values.jackrabbit.image.pullPolicy }}
                  env:
{{- with .Values.jackrabbit.env }}
{{ toYaml . | indent 22 }}
{{- end }}
                  volumeMounts:
                      - name: {{ include "jackrabbit.fullname" . }}-data
                        mountPath: /opt/jackrabbit/repository
                  ports:
                      - name: http
                        containerPort: 8080
                        protocol: TCP
                  readinessProbe:
                      httpGet:
                          path: /
                          port: http
