kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: {{ .Release.Name }}-mediaproxy
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
    storageClassName: do-block-storage
